name: SyncUpstream
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync repo
        uses: wei/pull@master
        with:
          upstream: cmliu/edgetunnel:main
          remote: origin
          branch: main

