name: SyncUpstream
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Sync from upstream
        uses: wei/pull@master
        with:
          upstream: cmliu/edgetunnel:main
          remote: origin
          branch: main
