name: Update GeoIP
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Git
        run: |
          git config --global user.name "tianyake9"
          git config --global user.email "你的GitHub邮箱"
      - name: Run update script
        run: |
          chmod +x update_geoip.sh
          ./update_geoip.sh
      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Update GeoIP data" || echo "No changes to commit"
          git push

