name: 自动更新节点&规则
on:
  push:
  schedule:
    - cron: '0 0 * * *'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          curl -fsSL https://github.com/MetaCubeX/meta-rules-dat/releases/latest/download/geoip.dat -o geoip.dat
          curl -fsSL https://github.com/MetaCubeX/meta-rules-dat/releases/latest/download/geosite.dat -o geosite.dat
          curl -fsSL "https://miyi-71l.pages.dev/sub?token=cc7169dfdfbe6a11c987d1d9ce8f92af&target=clash" -o nodes.yaml
      - run: |
          git config user.name bot
          git config user.email bot@github.com
          git add .
          git commit -m auto-update || true
          git push
